### ISSUE TITLE
Generating lineup

### ISSUE THREAD

**Issue by pherny** [brendanbrzycki/DailyFantasy#1]
Is there a readme on how to import projections and generate a lineup?

**Comment by brendanbrzycki** [comment]
Although assemble_lineup.py can successfully produce a lineup from given data, the project currently only contains code for retrieving historical data, not projections. It is possible to manually import projections and contest salaries into a Pandas DataFrame and pass that into the `data` variable within the main() function of assemble_lineup.py if you are just looking for some concrete results.
